name: Deploy MultiDocker
on:
  push:
    branches:
      - master 
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t tcheryph/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true tcheryph/react-test npm test
 
      - run: docker build -t tcheryph/multi-client ./client
      - run: docker build -t tcheryph/multi-nginx ./nginx
      - run: docker build -t tcheryph/multi-server ./server
      - run: docker build -t tcheryph/multi-worker ./worker
 
      - run: docker push tcheryph/multi-client
      - run: docker push tcheryph/multi-nginx
      - run: docker push tcheryph/multi-server
      - run: docker push tcheryph/multi-worker